### ISSUE TITLE
removing blocks does not work for the first block placed by player

### ISSUE THREAD

**Issue by bitlogist** [dgreenheck/minecraft-threejs-clone#10]
# Steps
1. Start game through menu
2. Place 1 block of stone, coal, or iron
3. Click on the block after switching to pickaxe to *try* and break it
4. Realize that the block will not break

# Details
This issue only happens with the 1st block the player places for some reason. These blocks are immune to this behavior:
- grass
- dirt

I have no idea why this happens because I still get log messages saying that the `id` has been set to `0` in the console.

**Comment by bitlogist** [comment]
I also figured that collisions with this glitched block didn't work. I think it's something to do with the rendering of the blocks.

**Comment by dgreenheck** [comment]
Thanks for reporting this. I will take a look soon.

**Comment by dgreenheck** [comment]
Identified some logic that was returning early if `!instanceId` evaluated to true. This logic would evaluate to true in the case `instanceId` is set to 0 (since 0 is falsey), which is erroneous since 0 is a valid instance id. Will go through the code and update logic to `instanceId !== null`.

**Comment by dgreenheck** [comment]
Followed repro steps after deploying fix and verified issue has been resolved.
