### ISSUE TITLE
Some of tree trunks remain displayed despite being removed

### ISSUE THREAD

**Issue by rafalspa** [dgreenheck/minecraft-threejs-clone#11]
### Steps
1. Launch new game
2. Stay on seed 0
3. Walk forward until the sand ends and the grass starts
4. Approach the first tree on right hand side which is kind of double tree glued together (player coords will be x 37, y 7, z 15 when standing in front of the tree)
5. Destroy the block first from the bottom
6. It is removed, console.log says it's removed as well, player can walk through it, however it remains displayed on the screen
It happens with other random trees as well, not only double ones, however one mentioned above is the easiest to recreate the bug.

### Details
Not sure if this only applies to tree block, I think I recall having the same issue with grass block on a different seed. Issue might not lay in removing the block itself, maybe it has something to do with the chunk rendering, e.g. the block lays in a specific coordinates

**Comment by dgreenheck** [comment]
Followed repro steps after fix and verified this issue has been resolved.
