### ISSUE TITLE
How do you create blocks in the air?

### ISSUE THREAD

**Issue by 2arch** [dgreenheck/minecraft-threejs-clone#14]
Hi, first of all, thank you so much for putting together this series. It is very high quality, and your explanations are crystal clear.

I was wondering how you might extend the addBlock function to add a blocks in the air without it being attached to anything?

```
  addBlock(x, y, z, blockId) {
    const coords = this.worldToChunkCoords(x, y, z);
    const chunk = this.getChunk(coords.chunk.x, coords.chunk.y, coords.chunk.z);

    if (chunk) {
      chunk.addBlock(coords.block.x, coords.block.y, coords.block.z, blockId);

      // Hide any blocks that may be totally obscured
      this.hideBlockIfNeeded(x - 1, y, z);
      this.hideBlockIfNeeded(x + 1, y, z);
      this.hideBlockIfNeeded(x, y - 1, z);
      this.hideBlockIfNeeded(x, y + 1, z);
      this.hideBlockIfNeeded(x, y, z - 1);
      this.hideBlockIfNeeded(x, y, z + 1);
    }
  }
```

Thank you in advance!

Looking forward to the rest of the videos :)

**Comment by dgreenheck** [comment]
Clouds are generated in the air without being attached to anything ([link to code](https://github.com/dgreenheck/minecraft-threejs-clone/blob/07a50a5ee3e390de334f467c6a4f553dd564f636/scripts/worldChunk.js#L192)).

Was there something else you had in mind?

**Comment by 2arch** [comment]
Yeah, I think what I'm looking for is for the player to be able to add a block in the air, rather than it be a part of world gen!

**Comment by dgreenheck** [comment]
You would have to modify [`updateRaycaster()`](https://github.com/dgreenheck/minecraft-threejs-clone/blob/07a50a5ee3e390de334f467c6a4f553dd564f636/scripts/player.js#L105). If the raycaster doesn't intersect with any blocks, then fallback to some new code that would place the selection indicator a few blocks in front of the player based on where they are looking.
