### ISSUE TITLE
 Own Bug and a Question

### ISSUE THREAD

**Issue by Crazywane** [dgreenheck/minecraft-threejs-clone#17]
Hi,
During the Update, you reintroduced the old bug.

```
// Don't allow removing the first layer of blocks
if (coords.block.y === 0) return;
```
    

And a question, how can I limit the world... for example, x: 2000, y: 2000?

**Comment by dgreenheck** [comment]
Thanks for catching that. Issue has been fixed.

As for limiting the world size, you would need to add some logic into `world.js` to prevent chunks being generated past a certain distance (most likely in the `generate()` method).
