### ISSUE TITLE
[Feature] Proper MC Java Movement

### ISSUE THREAD

**Issue by LightslicerGP** [dgreenheck/minecraft-threejs-clone#5]
This is an amazing project, I've never seen anything like it, especially with a tutorial series along with it is amazing!

I did want to point out the movement, there's a [Wiki for Minecraft Parkourists](https://www.mcpk.wiki/wiki/Player_Movement) that shows the formulas for how Minecraft Java handles movement, and I was wondering if you would be able to implement that?

**Comment by dgreenheck** [comment]
> This is an amazing project, I've never seen anything like it, especially with a tutorial series along with it is amazing!
> 
> I did want to point out the movement, there's a [Wiki for Minecraft Parkourists](https://www.mcpk.wiki/wiki/Player_Movement) that shows the formulas for how Minecraft Java handles movement, and I was wondering if you would be able to implement that?

I do not have plans to update the movement logic, but feel free to submit a PR if you would like to implement it.
