### ISSUE TITLE
collision helper

### ISSUE THREAD

**Issue by Akinaru** [dgreenheck/minecraft-threejs-clone#6]
Hey, i am currently trying to implements the collisions and i am at the helper part. When i have blocks that i can collide with, they become red but not transparent, and when i goi away, they are still red and won't disappear. And it's the same for contact points. Where the problem can come from ?
<img width="670" alt="image" src="https://github.com/dgreenheck/minecraft-threejs-clone/assets/90217410/b2d8c8df-6df8-413e-9685-b1237e9f7d8a">

**Comment by dgreenheck** [comment]
You need to clear your helpers each time you run the collision detection code. That will fix both issues.

```
  detectCollisions(player, world) {
    player.onGround = false;
    this.helpers.clear();  // <-- You are missing this line here

    const candidates = this.broadPhase(player, world);
    const collisions = this.narrowPhase(candidates, player);
  
    if (collisions.length > 0) {
      this.resolveCollisions(collisions, player);
    }
  }
```
